### ISSUE TITLE
Possible error with Redis 1.0

### ISSUE THREAD

**Issue by mudphone** [ragnard/redis-clojure#1]
Hi ragnard,

We're using your redis-clojure library over here, and we're noticing a strange exception:

(redis/with-server user/summarizer-redis-spec (redis/smembers "SESSIONS"))
java.lang.Exception: Could not read correct number of bytes (NO_SOURCE_FILE:0)

I'm wondering if this is because we recently started using Redis 1.0.  We had originally started using your library with 0.9 and all was well.

Is this project still in use?  Also, do you think it's worth us patching it, if it needs to be upgraded?

Thanks,
Kyle

**Comment by ragnard** [comment]
Hi Kyle,
Thanks for the report. I haven't been using redis-clojure for a while.

It's probably due to Redis 1.0. I will take a look at this tonight.

Thanks,
Ragge

**Comment by mudphone** [comment]
Hi Ragge,

It turns out that we were pegging our Redis server with thousands of queries in a very short period of time.  We believe that this was taking up open file (or socket resources) from the OS.  Even though we were closing our connections to Redis after using them, the time taken by the OS to reclaim the resources was too long.

So now, after reducing the number of connections we make to Redis, this error is no longer showing up.  It was always intermittent... i.e. it showed up after a long run of our app, but then went away later.

I just wanted to let you know of our progress, so that we don't send you on a wild goose chase.  As for supporting Redis 1.01, that's what we're using.  So, we're all for you taking a look!  (even if it's not to fix our bug)

Thanks!
Kyle

**Comment by ragnard** [comment]
Ok, thanks for the update.

I will put on my gloves and bring redis-clojure up-to-date with Redis 1.01 anyway. If you have had any other problems, or have any suggestions (interface, for example), please tell me.

As a step towards the next release, I will probably introduce Maven as project management and build tool. I will also make sure Salvatore includes the pre-built jar in client-libraries so you can just grab that if you're not into the whole Maven thing.

Thanks,
/Ragge
