### ISSUE TITLE
don't set *warn-on-reflection*

### ISSUE THREAD

**Issue by jwr** [ragnard/redis-clojure#13]
Caused by: java.lang.IllegalStateException: Can't change/establish root binding of: _warn-on-reflection_ with set (internal.clj:1)

this happens if someone sets :warn-on-reflection true in their project.clj file.

**Comment by ragnard** [comment]
I believe this was fixed in http://github.com/ragnard/redis-clojure/commit/a6710d030d3178804ad513c794028e701f71d6a0

Pushed to clojars.

**Comment by jwr** [comment]
Right. I'm sorry, I'm doing things in a hurry and generating noise.

I had my own forked version and did not notice this.

**Comment by ragnard** [comment]
No problem, I appreciate any feedback, but someone else was first this time... :)
