### ISSUE TITLE
Clojars

### ISSUE THREAD

**Issue by tom-pang** [ragnard/redis-clojure#2]
It would be very easy to push this project to clojars with lein, to make distribution easier. (see http://clojars.org/)

**Comment by ragnard** [comment]
Absolutely, it's already on my TODO list... Don't have much time these days.

**Comment by tom-pang** [comment]
http://clojars.org/redis/redis-clojure here for now. Was a simple 

ant -Dclojure.jar=/path/to/clojure.jar
scp pom.xml redis-clojure.jar clojars@clojars.org:

**Comment by tom-pang** [comment]
Now you're using lein, `lein push` from the same dir project.clj is in

**Comment by ragnard** [comment]
Pushed to Clojars:
http://clojars.org/redis-clojure

Thanks!
