### ISSUE TITLE
Unknown Reply Type

### ISSUE THREAD

**Issue by mudphone** [ragnard/redis-clojure#4]
Hi Ragnard,

I just started getting the following Exception when using the latest from master (below).  I saw this with Redis Server 1.01 and 1.02.  I'm running some experiments to try to find out what the bad response is exactly

But in the meantime, I thought I would ask if you have seen this before.

Thanks,
Kyle

2009-12-04 12:49:24: java.lang.Exception
Unknown reply type:
redis.internal$eval__2224$fn__2226.invoke(internal.clj:113)
clojure.lang.MultiFn.invoke(MultiFn.java:157)
redis.internal$read_reply__2220.invoke(internal.clj:109)
redis.internal$read_reply__2220.invoke(internal.clj:107)
redis$get__2369.invoke(redis.clj:63)

**Comment by mudphone** [comment]
I haven't seen this error for some time.  So, I would close it.

**Comment by ragnard** [comment]
Okay. Haven't been able to reproduce either. Thanks for the report anyway.

**Comment by parag** [comment]
Hello Kyle, 
I recently wrote a Redis Client library in Java and figured out that Redis unexpectedly returns a reply type other than (+,:,\* or $). Just wondering if you were able to figure out a solution.

**Comment by mudphone** [comment]
Hi Parag,

GeorgeJahad and I have been experimenting and have noticed the  same.  In our case, we seem to be getting this error when our Redis connection pool hands us a connection which has timed out.  We were able to avoid this error by verifying that our connections were valid/active, before borrowing them from the pool.  Hope that helps.

**Comment by parag** [comment]
Exactly. Was just to reply. I too was having problem with connection pool. Socket connection must be sending some negative reply which we are not quite handling. Thanks by the way. Setting timeout to 0 (disabling it) in redis server configuration file also solves the problem though
