### ISSUE TITLE
Could not read correct number of bytes

### ISSUE THREAD

**Issue by mudphone** [ragnard/redis-clojure#8]
user=> (in-repl (redis/keys "*"))
cbuf is: #<char[] [C@777d57d6>
cbuf as str: random-key-2-1263428249967-817409 random-key-4-1263428249966-157483
java.lang.Exception: Could not read correct number of bytes (NO_SOURCE_FILE:82)

This is the error I'm seeing when trying to get a long list of keys back from Redis-Clojure.  "in-repl" is a macro which wraps a call to "redis/with-server" and hands it my connection spec.

Have you seen this error before?  I added some code to redis/internal.clj to print out the cbuf that is read from Redis.  It looks like only some of the correct value is returned, but not all.  The strange thing is that if I do a "keys *" in telnet, the correct return value is given.  So, all is well in telnet at the same time that this error appears via Redis-Clojure.

Thanks,
Kyle

**Comment by mudphone** [comment]
Strange, this shows up as created by [deleted user].  But, it was created by me, "mudphone".

**Comment by ragnard** [comment]
Do you still have this problem with newer/edge Redis and redis-clojure?

**Comment by mudphone** [comment]
I haven't been working with this for a while, so I'll close this.
