### ISSUE TITLE
authentication doesn't work

### ISSUE THREAD

**Issue by neilmock** [ragnard/redis-clojure#9]
looks like the client is trying to select a db before auth as part of the with-server macro, which fails if authentication is turned on.

I've got a proposed fix here:  http://github.com/neilmock/redis-clojure/commit/aaf85ab4222529de4d1b10fc07c6ab6f17524d37

Will issue a pull request but if you guys have a better fix that is fine too.  Thanks!

**Comment by ragnard** [comment]
Thank you very much for the fix, merged and appreciated!
